apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: relyonlyurself/first-repo:58f521ab1e9472ffe3cb1f2e3ed6547d69e7b9ed
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-uri
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-password
