apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: relyonlyurself/first-repo:fbccd20054d3942edc2c3fe0776cc3ad68ef3665
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-uri
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-password
